# The URL the site will be built for
base_url = "https://docs.simpleiot.org"
description = "Simple IoT Documentation"

theme = "book"
compile_sass = true
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
